################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Core/ThreadSafe \
Drivers/SSD1963/Src \
Drivers/STM32H7xx_HAL_Driver/Src \
Drivers/io \
Drivers/screen \
Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src \
Middlewares/ST/STM32_USB_Host_Library/Core/Src \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
USB_HOST/App \
USB_HOST/Target \
lvgl/demos/benchmark/assets \
lvgl/demos/benchmark \
lvgl/demos/flex_layout \
lvgl/demos/keypad_encoder \
lvgl/demos \
lvgl/demos/multilang/assets/avatars \
lvgl/demos/multilang/assets/emojis \
lvgl/demos/multilang/assets/fonts \
lvgl/demos/multilang/assets \
lvgl/demos/multilang \
lvgl/demos/music/assets \
lvgl/demos/music \
lvgl/demos/scroll \
lvgl/demos/stress \
lvgl/demos/transform/assets \
lvgl/demos/transform \
lvgl/demos/widgets/assets \
lvgl/demos/widgets \
lvgl/env_support/pikascript \
lvgl/env_support/rt-thread \
lvgl/env_support/rt-thread/squareline \
lvgl/examples/anim \
lvgl/examples/assets \
lvgl/examples/assets/emoji \
lvgl/examples/event \
lvgl/examples/get_started \
lvgl/examples/layouts/flex \
lvgl/examples/layouts/grid \
lvgl/examples/libs/barcode \
lvgl/examples/libs/bmp \
lvgl/examples/libs/ffmpeg \
lvgl/examples/libs/freetype \
lvgl/examples/libs/gif \
lvgl/examples/libs/libjpeg_turbo \
lvgl/examples/libs/libpng \
lvgl/examples/libs/lodepng \
lvgl/examples/libs/qrcode \
lvgl/examples/libs/rlottie \
lvgl/examples/libs/tiny_ttf \
lvgl/examples/libs/tjpgd \
lvgl/examples/others/file_explorer \
lvgl/examples/others/fragment \
lvgl/examples/others/gridnav \
lvgl/examples/others/ime \
lvgl/examples/others/imgfont \
lvgl/examples/others/monkey \
lvgl/examples/others/observer \
lvgl/examples/others/snapshot \
lvgl/examples/porting \
lvgl/examples/scroll \
lvgl/examples/styles \
lvgl/examples/widgets/animimg \
lvgl/examples/widgets/arc \
lvgl/examples/widgets/bar \
lvgl/examples/widgets/btn \
lvgl/examples/widgets/btnmatrix \
lvgl/examples/widgets/calendar \
lvgl/examples/widgets/canvas \
lvgl/examples/widgets/chart \
lvgl/examples/widgets/checkbox \
lvgl/examples/widgets/dropdown \
lvgl/examples/widgets/img \
lvgl/examples/widgets/imgbtn \
lvgl/examples/widgets/keyboard \
lvgl/examples/widgets/label \
lvgl/examples/widgets/led \
lvgl/examples/widgets/line \
lvgl/examples/widgets/list \
lvgl/examples/widgets/menu \
lvgl/examples/widgets/msgbox \
lvgl/examples/widgets/obj \
lvgl/examples/widgets/roller \
lvgl/examples/widgets/scale \
lvgl/examples/widgets/slider \
lvgl/examples/widgets/span \
lvgl/examples/widgets/spinbox \
lvgl/examples/widgets/spinner \
lvgl/examples/widgets/switch \
lvgl/examples/widgets/table \
lvgl/examples/widgets/tabview \
lvgl/examples/widgets/textarea \
lvgl/examples/widgets/tileview \
lvgl/examples/widgets/win \
lvgl/src/core \
lvgl/src/dev/display/drm \
lvgl/src/dev/display/fb \
lvgl/src/dev/display/tft_espi \
lvgl/src/dev/nuttx \
lvgl/src/dev/sdl \
lvgl/src/display \
lvgl/src/draw \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/nxp/vglite \
lvgl/src/draw/sw/blend \
lvgl/src/draw/sw \
lvgl/src/font \
lvgl/src/indev \
lvgl/src/layouts/flex \
lvgl/src/layouts/grid \
lvgl/src/layouts \
lvgl/src/libs/barcode \
lvgl/src/libs/bmp \
lvgl/src/libs/ffmpeg \
lvgl/src/libs/freetype \
lvgl/src/libs/fsdrv \
lvgl/src/libs/gif \
lvgl/src/libs/libjpeg_turbo \
lvgl/src/libs/libpng \
lvgl/src/libs/lodepng \
lvgl/src/libs/qrcode \
lvgl/src/libs/rlottie \
lvgl/src/libs/tiny_ttf \
lvgl/src/libs/tjpgd \
lvgl/src \
lvgl/src/misc \
lvgl/src/osal \
lvgl/src/others/file_explorer \
lvgl/src/others/fragment \
lvgl/src/others/gridnav \
lvgl/src/others/ime \
lvgl/src/others/imgfont \
lvgl/src/others/monkey \
lvgl/src/others/observer \
lvgl/src/others/snapshot \
lvgl/src/others/sysmon \
lvgl/src/stdlib/builtin \
lvgl/src/stdlib/clib \
lvgl/src/stdlib \
lvgl/src/stdlib/micropython \
lvgl/src/themes/basic \
lvgl/src/themes/default \
lvgl/src/themes \
lvgl/src/themes/mono \
lvgl/src/tick \
lvgl/src/widgets/animimage \
lvgl/src/widgets/arc \
lvgl/src/widgets/bar \
lvgl/src/widgets/button \
lvgl/src/widgets/buttonmatrix \
lvgl/src/widgets/calendar \
lvgl/src/widgets/canvas \
lvgl/src/widgets/chart \
lvgl/src/widgets/checkbox \
lvgl/src/widgets/dropdown \
lvgl/src/widgets/image \
lvgl/src/widgets/imgbtn \
lvgl/src/widgets/keyboard \
lvgl/src/widgets/label \
lvgl/src/widgets/led \
lvgl/src/widgets/line \
lvgl/src/widgets/list \
lvgl/src/widgets/menu \
lvgl/src/widgets/msgbox \
lvgl/src/widgets/objx_templ \
lvgl/src/widgets/roller \
lvgl/src/widgets/scale \
lvgl/src/widgets/slider \
lvgl/src/widgets/span \
lvgl/src/widgets/spinbox \
lvgl/src/widgets/spinner \
lvgl/src/widgets/switch \
lvgl/src/widgets/table \
lvgl/src/widgets/tabview \
lvgl/src/widgets/textarea \
lvgl/src/widgets/tileview \
lvgl/src/widgets/win \
lvgl/tests/makefile \
lvgl/tests/src \
lvgl/tests/src/test_assets \
lvgl/tests/src/test_cases \
lvgl/tests/src/test_cases/draw \
lvgl/tests/src/test_cases/libs \
lvgl/tests/src/test_cases/widgets \
lvgl/tests/unity \

